# Generated by Django 5.1.7 on 2025-04-02 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIAnalysis',
            fields=[
                ('analysis_id', models.AutoField(primary_key=True, serialize=False)),
                ('student_exam_id', models.IntegerField()),
                ('category', models.CharField(choices=[('Arithmetic', 'Arithmetic'), ('Trigonometry', 'Trigonometry'), ('Algebra', 'Algebra'), ('Geometry', 'Geometry'), ('Calculus', 'Calculus')], max_length=50)),
                ('score_percentage', models.FloatField(default=0.0)),
                ('improvement_tips', models.TextField(null=True)),
            ],
            options={
                'db_table': 'AI_Analysis',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AIQuiz',
            fields=[
                ('quiz_id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('Arithmetic', 'Arithmetic'), ('Trigonometry', 'Trigonometry'), ('Algebra', 'Algebra'), ('Geometry', 'Geometry'), ('Calculus', 'Calculus')], max_length=50)),
                ('difficulty', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], max_length=10)),
                ('ai_generated', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Quizzes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('answer_id', models.AutoField(primary_key=True, serialize=False)),
                ('student_exam_id', models.IntegerField()),
                ('question_id', models.IntegerField()),
                ('student_answer', models.CharField(max_length=255)),
                ('is_correct', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'Answers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Doubt',
            fields=[
                ('doubt_id', models.AutoField(primary_key=True, serialize=False)),
                ('student_id', models.IntegerField()),
                ('question_text', models.TextField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Answered', 'Answered')], default='Pending', max_length=10)),
                ('ai_response', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Doubts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ParentStudentMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_id', models.IntegerField()),
                ('student_id', models.IntegerField()),
            ],
            options={
                'db_table': 'Parent_Student_Mapping',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('quiz_id', models.AutoField(primary_key=True, serialize=False)),
                ('teacher_id', models.IntegerField()),
                ('quiz_title', models.CharField(max_length=255)),
                ('total_marks', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'quiz',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_id', models.IntegerField()),
                ('question_id', models.IntegerField()),
            ],
            options={
                'db_table': 'Quiz_Questions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.IntegerField(primary_key=True, serialize=False)),
                ('parent_id', models.IntegerField(null=True)),
                ('grade_level', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Students',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StudentExam',
            fields=[
                ('student_exam_id', models.AutoField(primary_key=True, serialize=False)),
                ('student_id', models.IntegerField()),
                ('quiz_id', models.IntegerField()),
                ('score', models.IntegerField(default=0)),
                ('taken_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Student_Exams',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('teacher_id', models.IntegerField(primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=100)),
                ('experience', models.IntegerField()),
            ],
            options={
                'db_table': 'Teachers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('question_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('Arithmetic', 'Arithmetic'), ('Trigonometry', 'Trigonometry'), ('Algebra', 'Algebra'), ('Geometry', 'Geometry'), ('Calculus', 'Calculus')], max_length=50)),
                ('question_text', models.TextField()),
                ('ansType', models.TextField()),
                ('answers', models.TextField()),
                ('correct_answer', models.CharField(max_length=255)),
                ('difficulty_level', models.CharField(choices=[('kindergartens', 'kindergartens'), ('year_1', 'year_1'), ('year_2', 'year_2'), ('year_3', 'year_3'), ('year_4', 'year_4'), ('year_5', 'year_5'), ('year_6', 'year_6'), ('year_7', 'year_7'), ('year_8', 'year_8'), ('year_9', 'year_9'), ('year_10', 'year_10'), ('year_11', 'year_11'), ('year_12', 'year_12')], max_length=13)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'questions',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('fullName', models.CharField(blank=True, max_length=255, null=True)),
                ('password', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=50)),
                ('academicLevel', models.TextField()),
                ('userStatus', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
