# Generated by Django 5.1.7 on 2025-04-19 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='quizquestion',
            table='quiz_questions',
        ),
    ]
