# Generated by Django 5.1.7 on 2025-03-30 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIQuiz',
            fields=[
                ('quiz_id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('Arithmetic', 'Arithmetic'), ('Trigonometry', 'Trigonometry'), ('Algebra', 'Algebra'), ('Geometry', 'Geometry'), ('Calculus', 'Calculus')], max_length=50)),
                ('difficulty', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], max_length=10)),
                ('ai_generated', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Quizzes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_id', models.IntegerField()),
                ('question_id', models.IntegerField()),
            ],
            options={
                'db_table': 'Quiz_Questions',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='QuizSystem',
        ),
        migrations.AlterModelOptions(
            name='aianalysis',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='answer',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='doubt',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='parentstudentmapping',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='quiz',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='studentexam',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'managed': False},
        ),
    ]
