# Generated by Django 5.1.7 on 2025-04-01 14:13

from django.db import migrations

from django.contrib.auth.hashers import make_password
from myapp.models import User

def create_default_user(apps, schema_editor):
    # Check if the default user already exists to avoid duplication
    if not User.objects.filter(username='user').exists():
        User.objects.create(
            username='user',
            email='admin@admin.com',
            firstName='Admin',
            lastName='User',
            fullName='Admin User',
            password=make_password('password'),  
            role='teacher',
            academicLevel='N/A',
            userStatus='active'
        )

class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_default_user),
    ]
