# Generated by Django 5.1.7 on 2025-03-16 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_aianalysis_answer_doubt_parentstudentmapping_and_more'),
    ]

    operations = [
    ]
