# Generated by Django 5.1.7 on 2025-04-20 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_create_default_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='quiz_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='score',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterModelTable(
            name='quizquestion',
            table='quiz_questions',
        ),
    ]
