# Generated by Django 5.1.7 on 2025-05-01 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_create_default_user'),
        ('myapp', '0003_auto_20250501_1458'),
    ]

    operations = [
    ]
