# Generated by Django 5.1.7 on 2025-03-30 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_aianalysis_table_alter_answer_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='question',
            table='questions',
        ),
    ]
