# Generated by Django 5.1.7 on 2025-03-16 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20250316_1116'),
    ]

    operations = [
    ]
