# Generated by Django 5.1.7 on 2025-04-20 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_quiz_quiz_status_quizquestion_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='quiz_level',
            field=models.CharField(default='year_1', max_length=50),
        ),
    ]
