# Generated by Django 5.1.7 on 2025-05-03 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_merge_20250501_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='student_mark',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='answer',
            name='teacher_comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
