# Generated by Django 5.1.7 on 2025-03-16 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20250316_1209'),
    ]

    operations = [
    ]
