# Generated by Django 5.1.7 on 2025-03-16 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20250316_1534'),
    ]

    operations = [
    ]
