# Generated by Django 5.1.7 on 2025-03-16 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20250316_1609'),
    ]

    operations = [
    ]
