# Generated by Django 5.1.7 on 2025-03-20 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_auto_20250316_1626'),
    ]

    operations = [
    ]
