# Generated by Django 5.1.7 on 2025-03-21 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_auto_20250320_1404'),
    ]

    operations = [
    ]
