# Generated by Django 5.1.7 on 2025-03-21 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_auto_20250322_0735'),
    ]

    operations = [
    ]
