# Generated by Django 5.1.7 on 2025-03-26 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_auto_20250322_0819'),
    ]

    operations = [
    ]
