# Generated by Django 5.1.7 on 2025-03-26 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_auto_20250326_1638'),
    ]

    operations = [
    ]
