# Generated by Django 5.1.7 on 2025-03-26 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_auto_20250326_1651'),
    ]

    operations = [
    ]
