# Generated by Django 5.1.7 on 2025-03-26 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_auto_20250326_2116'),
    ]

    operations = [
    ]
