# Generated by Django 5.1.7 on 2025-03-26 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0032_auto_20250326_2129'),
    ]

    operations = [
    ]
