# Generated by Django 5.1.7 on 2025-03-26 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0034_auto_20250326_2132'),
    ]

    operations = [
    ]
